server:
  port: 10011
#logging:
#  level:
#    cn.itcast: debug
#  pattern:
#    dateformat: MM-dd HH:mm:ss:SSS
spring:
  application:
    name: gateways
  cloud:
    nacos:
      discovery:
        server-addr: 121.43.101.184:8848
#       discovery:
#         namespace: 180ff210-4b23-465c-a596-b52c751d2edc


    gateway:
      routes:
        - id: student    # 路由标示，必须唯一
          uri: lb://student   # 路由的目标地址
          predicates:     # 路由断言，判断请求是否符合规则
          - Path=/student/**       # 路径断言，判断路径是否是以/user开头，如果是则符合
        - id: teacher
          uri: lb://teacher
          predicates:
          - Path=/teacher/**
        - id: video
          uri: lb://video
          predicates:
          - Path=/video/**
        - id: oss
          uri: lb://oss
          predicates:
          - Path=/oss/**
        - id: excel
          uri: lb://excel
          predicates:
          - Path=/excel/**
        - id: admin
          uri: lb://admin
          predicates:
          - Path=/admin/**,/sys/**

#spring:
#  cloud:
#    gateway:
#      httpclient:
#        #默认为毫秒单位，connect-timeout 默认时长为45s
#        connect-timeout: 5000
#        #点进源码可设置不同单位，我这里设置为5s
#        response-timeout: 5s
#      routes:
#        - id: server-product
#          uri: lb://demo-product
#          predicates:
#            - Path=/lei-app/product/**,/zs/{aa}
#          filters:
#            - StripPrefix=1
#          # 针对于当前路由的http超时时间设置
#          metadata:
#            response-timeout: 2000
#            connect-timeout: 2000

