server:
  port: 9999
# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://162.14.113.138:3306/exam?characterEncoding=UTF8&autoReconnect=true&useSSL=false&rewriteBatchedStatements=true
    username: exam
    password: 7nDNsJKiYSa2NkWE
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
#        namespace: 180ff210-4b23-465c-a596-b52c751d2edc
        server-addr: 162.14.113.138:8848
  application:
   name: teachers
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  mail:
    username: 907167912@qq.com
    password: whbiswbfobqxbajh
    default-encoding: UTF-8
    protocol: smtp
    host: smtp.qq.com
  messages:
    basename: i18n/messages
  profiles:
      active: prod
  mvc:
    hiddenmethod:
      filter:
        enabled: true




mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
  configuration:
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志文件


aliyun:
  endPoint: oss-cn-beijing.aliyuncs.com
  urlPrefix: http://lvyiting.oss-cn-beijing.aliyuncs.com/
  accessKeyId: LTAI5t993RxFv7iC7AcBWcaW
  accessKeySecret: 5GduvEROBXuJ87qf0wH26olpIqhsqN
  bucketName: lvyiting
  fileHost: files
  vod:
    file:
      keyid: LTAI5t993RxFv7iC7AcBWcaW
      keysecret: 5GduvEROBXuJ87qf0wH26olpIqhsqN





