server:
  port: 9004
# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://162.14.113.138:3306/exam?characterEncoding=UTF8&autoReconnect=true&useSSL=false&rewriteBatchedStatements=true
    username: exam
    password: 7nDNsJKiYSa2NkWE
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        namespace: 180ff210-4b23-465c-a596-b52c751d2edc
        server-addr:  162.14.113.138:8848 # nacos地址
  application:
   name: student


mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
  configuration:
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志文件




