server:
  port: 9005

spring:
  datasource:
    url: jdbc:mysql://162.14.113.138:3306/exam?characterEncoding=UTF8&autoReconnect=true&useSSL=false
    username: exam
    password: 7nDNsJKiYSa2NkWE
    driver-class-name: com.mysql.jdbc.Driver

  application:
    name: excel
  cloud:
    nacos:
      server-addr: 162.14.113.138:8848 # nacos地址
      discovery:
        namespace: 180ff210-4b23-465c-a596-b52c751d2edc


